function hodyJelinkova = nactihody(filename, dataLines)
%IMPORTFILE Import data from a text file
%  HODYJELINKOVA = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the numeric data.
%
%  HODYJELINKOVA = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  hodyJelinkova = nactihody("hody-Jelinkova.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Jan-2026 22:21:14

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["VarName1", "VarName2"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
hodyJelinkova = readtable(filename, opts);

%% Convert to output type
hodyJelinkova = table2array(hodyJelinkova);
end